
DEFAULT_TOKEN_LEEWAY_SECONDS: int = 120

ROLE_ADMIN: str = "Admin"
ROLE_MANAGER: str = "Manager"
ROLE_EMPLOYEE: str = "Employee"

EMPLOYEE_STATUS_ACTIVE: str = "ACTIVE"
EMPLOYEE_STATUS_INACTIVE: str = "INACTIVE"

EMPLOYMENT_TYPES: tuple[str, ...] = ("Full-Time", "Part-Time", "Contract", "Intern")

DEFAULT_MAP_WIDTH: int = 1000
DEFAULT_MAP_HEIGHT: int = 800

SEAT_STATUS_VACANT: str = "Vacant"
SEAT_STATUS_OCCUPIED: str = "Occupied"
SEAT_STATUS_BLOCKED: str = "Blocked"

SEAT_TYPE_STANDARD: str = "Standard"
SEAT_TYPE_CUBICLE: str = "Cubicle"

SEAT_ACTION_ASSIGN: str = "ASSIGN"
SEAT_ACTION_RELEASE: str = "RELEASE"
SEAT_ACTION_RELOCATE: str = "RELOCATE"
SEAT_ACTION_SWAP: str = "SWAP"

ASSET_TYPE_LAPTOP: str = "Laptop"
ASSET_TYPE_DESKTOP: str = "Desktop"
ASSET_TYPE_MONITOR: str = "Monitor"
ASSET_TYPE_MOUSE: str = "Mouse"
ASSET_TYPE_EARPHONE: str = "Earphone"
ASSET_TYPE_CHARGER: str = "Charger"
ASSET_TYPES: tuple[str, ...] = (
    ASSET_TYPE_LAPTOP,
    ASSET_TYPE_DESKTOP,
    ASSET_TYPE_MONITOR,
    ASSET_TYPE_MOUSE,
    ASSET_TYPE_EARPHONE,
    ASSET_TYPE_CHARGER,
)

ASSET_STATUS_AVAILABLE: str = "Available"
ASSET_STATUS_ASSIGNED: str = "Assigned"
ASSET_STATUS_UNDER_MAINTENANCE: str = "Under Maintenance"
ASSET_STATUS_RETIRED: str = "Retired"
ASSET_STATUSES: tuple[str, ...] = (
    ASSET_STATUS_AVAILABLE,
    ASSET_STATUS_ASSIGNED,
    ASSET_STATUS_UNDER_MAINTENANCE,
    ASSET_STATUS_RETIRED,
)

ASSET_ACTION_ASSIGN: str = "ASSIGN"
ASSET_ACTION_RETURN: str = "RETURN"
ASSET_ACTION_MAINTENANCE: str = "MAINTENANCE"
ASSET_ACTION_REPLACE: str = "REPLACE"

REQUEST_TYPE_NEW_SEAT: str = "NEW_SEAT"
REQUEST_TYPE_RELOCATION: str = "RELOCATION"
REQUEST_TYPE_SWAP: str = "SWAP"
REQUEST_TYPE_ASSET_NEW: str = "ASSET_NEW"
REQUEST_TYPE_ASSET_MAINTENANCE: str = "ASSET_MAINTENANCE"
REQUEST_TYPE_ASSET_REPLACEMENT: str = "ASSET_REPLACEMENT"

REQUEST_STATUS_PENDING: str = "PENDING"
REQUEST_STATUS_PENDING_CONSENT: str = "PENDING_CONSENT"
REQUEST_STATUS_MANAGER_APPROVED: str = "MANAGER_APPROVED"
REQUEST_STATUS_REJECTED: str = "REJECTED"
REQUEST_STATUS_COMPLETED: str = "COMPLETED"
REQUEST_STATUS_CANCELLED: str = "CANCELLED"

NOTIFICATION_TYPE_REQUEST: str = "REQUEST"
NOTIFICATION_TYPE_APPROVAL: str = "APPROVAL"
NOTIFICATION_TYPE_EXECUTION: str = "EXECUTION"
NOTIFICATION_TYPE_SWAP_CONSENT: str = "SWAP_CONSENT"
NOTIFICATION_TYPE_ASSET: str = "ASSET"
